services:
  grocy:
    image: ghcr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Melbourne
    volumes:
      - ./grocy_data:/config
    ports:
      - 9283:80
    restart: unless-stopped

  barcodebuddy:
    build: ../barcodebuddy
    container_name: barcodebuddy
    environment:
      - BARCODESYSTEM=GROCY
      - GROCY_URL=http://grocy
    ports:
      - 9284:80
    restart: unless-stopped
    depends_on:
      - grocy
